### ISSUE TITLE
KafkaJSConsumerPrometheusExporter.consumerFetchDuration initialisation is missing

### ISSUE THREAD

**Issue by mivanilov** [christiangalsterer/kafkajs-prometheus-exporter#91]
Getting error after `kafkajs` consumer run starts:
{"level":"ERROR","timestamp":"2024-04-04T13:09:03.572Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNonRetriableError: Cannot read properties of undefined (reading 'observe')"...

Version 3.1.0

Bug on line https://github.com/christiangalsterer/kafkajs-prometheus-exporter/blob/main/src/kafkaJSConsumerPrometheusExporter.ts#L107 
`consumerFetchLatency` initialised second time instead of `consumerFetchDuration`

**Comment by christiangalsterer** [comment]
@mivanilov : A new release 3.1.1 is now available on NPM.

**Comment by mivanilov** [comment]
@christiangalsterer thanks, it works now!
