### ISSUE TITLE
Feature Request: support multiple registrations of metrics

### ISSUE THREAD

**Issue by odedino** [christiangalsterer/kafkajs-prometheus-exporter#97]
In order to support multiple consumer / producers it should be possible to call the monitor functions multiple times.
This will allow use cases such as new instances / multiple consumers to be supported.

**Comment by christiangalsterer** [comment]
Will be released with version 3.2.0

**Comment by christiangalsterer** [comment]
II just released 3.2.0 to npm. Thanks again for your contribution.
